[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]
preview = ["pixi-build"]
[package]
name = "parallel_rdkit"
license = "Apache-2.0"
license-file = "LICENSE"
authors = ["Nir Cohen"]
[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[environments]
test = { features = ["test"], solve-group = "default" }
gpu = {features= ["gpu"], solve-group="gpu"}
[feature.test.tasks]
test = { depends-on = ["test-fingerprint", "test-parallel"] }
test-full = { depends-on = ["test", "test-msready"] }
test-fingerprint = "pytest tests/test_fingerprint.py"
test-parallel = "pytest tests/test_parallel.py"
test-msready = "pytest tests/test_msready_full.py -D data/DSSTox.csv"
benchmark-msready = "python benchmarks/benchmark_msready.py"

[feature.test.dependencies]
parallel_rdkit = { path = "." }
pytest = "*"
numpy = "*"
polars = "*"
pyarrow = "*"
tqdm = "*"
rdkit = "*"
psutil = "*"


[feature.gpu.tasks]
test-matrix-similarity = "pytest tests/test_matrix_similarity.py -v"

[feature.gpu.target.linux-64.dependencies]
parallel_rdkit = { path = "." }
pytest = "*"
numpy = "*"
polars = "*"
pyarrow = "*"
tqdm = "*"
rdkit = "*"
psutil = "*"
nvmolkit="==0.2.0"
pytorch-gpu="*"
[feature.gpu.system-requirements]
cuda = "12.0"
