[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]
preview = ["pixi-build"]
[package]
name = "parallel_rdkit"
license = "Apache-2.0"
license-file = "LICENSE"
authors = ["Nir Cohen"]
[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }

[feature.test.tasks]
test = { depends-on = ["test-fingerprint", "test-parallel"] }
test-fingerprint = "pytest tests/test_fingerprint.py"
test-parallel = "pytest tests/test_parallel.py"

[feature.test.dependencies]
pytest = "*"
numpy = "*"
polars = "*"
pyarrow = "*"
tqdm = "*"
rdkit = "*"

[dependencies]
python = "3.12.*"
rattler-build = "*"
parallel_rdkit = { path = "." }
