context:
  name: "parallel_rdkit"
  version: "0.1.0"

package:
  name: "${{ name|lower }}"
  version: "${{ version }}"

source:
  path: .

build:
  number: 0
  script: |
    python -m pip install . --no-deps --no-build-isolation -vv
  python:
    version_independent: true

requirements:
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - python >=3.8,<3.13
    - pip
    - librdkit-dev
    - nanobind >=2.0
    - boost
    - scikit-build-core
  run:
    - python >=3.8,<3.13
    - rdkit
    - boost
    - polars
    - pyarrow
    - pytest
    - tqdm
    - numpy
    - pandas

tests:
  - python:
      imports:
        - parallel_rdkit

about:
  summary: "A parallel RDKit utilities implementation"
  license: Apache-2.0
