context:
    name: "parallel_rdkit"
    version: "0.2.0"

package:
    name: "${{ name|lower }}"
    version: "${{ version }}"

source:
    path: .

build:
    number: 0
    script:
        - if: win
          then: $RECIPE_DIR/build.bat
        - if: unix
          then: $RECIPE_DIR/build.sh
    python:
        version_independent: true

requirements:
    ignore_run_exports:
        by_name:
            - python_abi
    build:
        - ${{ compiler('cxx') }}
        - python >=3.8
        - pip
        - python-build
        - librdkit-dev
        - nanobind
        - boost
        - scikit-build-core
        - cmake
        - ninja
    host:
        - python >=3.8
        - pip
        - python-build
        - librdkit-dev
        - nanobind
        - boost
        - scikit-build-core
        - cmake
        - ninja
    run:
        - python >=3.8
        - rdkit
        - numpy

tests:
    - python:
          imports:
              - parallel_rdkit

about:
    summary: "A parallel RDKit utilities implementation"
    license: Apache-2.0
