context:
    name: "parallel_rdkit"
    version: "0.2.0"

package:
    name: "${{ name|lower }}"
    version: "${{ version }}"

source:
    path: .

build:
    number: 0
    script: |
        python -m build --wheel --outdir "$SRC_DIR/dist/wheels" --no-isolation --skip-dependency-check
        mkdir -p "$RECIPE_DIR/dist"
        cp "$SRC_DIR/dist/wheels/"*.whl "$RECIPE_DIR/dist/"
        python -m pip install "$SRC_DIR/dist/wheels/"*.whl --no-deps --no-build-isolation -vv
    python:
        version_independent: true

requirements:
    ignore_run_exports:
        by_name:
            - python_abi
    build:
        - ${{ compiler('cxx') }}
        - python >=3.8
        - pip
        - python-build
        - librdkit-dev
        - nanobind
        - boost
        - scikit-build-core
        - cmake
        - ninja
    host:
        - python >=3.8
        - pip
        - python-build
        - librdkit-dev
        - nanobind
        - boost
        - scikit-build-core
        - cmake
        - ninja
    run:
        - python >=3.8
        - rdkit
        - numpy

tests:
    - python:
          imports:
              - parallel_rdkit

about:
    summary: "A parallel RDKit utilities implementation"
    license: Apache-2.0
