import polars as pl
import pytest
import time

from parallel_rdkit import msready_inchi_inchikey_parallel


def get_msready_data(smiles_series: pl.Series) -> pl.DataFrame:
    """Returns DataFrame with columns: msready_smiles, inchi, inchikey"""
    smiles_list = smiles_series.to_list()
    num_smiles = len(smiles_list)

    start_time = time.perf_counter()
    msready_smiles, _, inchikeys = msready_inchi_inchikey_parallel(smiles_list)
    elapsed = time.perf_counter() - start_time

    time_per_smiles = elapsed / num_smiles if num_smiles > 0 else 0
    print(f"\n[MS-Ready Timing] Total: {elapsed:.3f}s | Count: {num_smiles} | Per SMILES: {time_per_smiles:.6f}s")

    return pl.DataFrame({
        "msready_smiles_generated": pl.Series(msready_smiles),
        "inchikey_msready": pl.Series(inchikeys)
    })


def test_msready_pubchem_join(msready_csv_path, pubchem_parquet_path, num_examples):
    if not msready_csv_path or not pubchem_parquet_path:
        pytest.skip("-D/--dump and -P/--pubchem-parquet args required for full test")
    
    if not msready_csv_path:
        pytest.skip(f"No CSV files found in dump path")

    schema = {
        "DTXSID": pl.String,
        "PREFERRED_NAME": pl.String,
        "CASRN": pl.String,
        "DTXCID": pl.String,
        "INCHIKEY": pl.String,
        "IUPAC_NAME": pl.String,
        "SMILES": pl.String,
        "MOLECULAR_FORMULA": pl.String,
        "AVERAGE_MASS": pl.Float64,
        "MONOISOTOPIC_MASS": pl.Float64,
        "QSAR_READY_SMILES": pl.String,
        "MS_READY_SMILES": pl.String,
        "IDENTIFIER": pl.String,
    }

    df_csv = pl.scan_csv(msready_csv_path, schema=schema)
    if num_examples is not None:
        df_csv = df_csv.head(num_examples)
    df_csv = df_csv.with_columns(
        pl.col("INCHIKEY").str.split("-").list.get(0).alias("base_inchikey")
    )

    df_pubchem = (
        pl.scan_parquet(str(pubchem_parquet_path), low_memory=True)
        .select(
            [
                pl.col("InChIKey").alias("inchikey_pubchem"),
                pl.col("SMILES").alias("smiles_pubchem"),
            ]
        )
        .with_columns(
            pl.col("inchikey_pubchem").str.split("-").list.get(0).alias("base_inchikey")
        )
        # Deduplicate pubchem by base_inchikey
        .unique(subset="base_inchikey")
    )

    # join them
    joined_lf = df_csv.join(df_pubchem, on="base_inchikey")
    
    # run it all with lazyframes, streaming engine first to get smiles
    joined_df = joined_lf.collect(engine="streaming")
    
    # Apply MS-Ready conversion and get generated smiles + inchikeys
    msready_data = get_msready_data(joined_df["smiles_pubchem"])
    
    # Combine results
    joined_df = joined_df.with_columns([
        msready_data["msready_smiles_generated"],
        msready_data["inchikey_msready"]
    ]).with_columns(
        pl.col("inchikey_msready")
        .str.split("-")
        .list.get(0)
        .alias("base_inchikey_msready")
    )
    
    # Filter mismatches, excluding expected inorganics (both code and dump agree no MS-Ready form)
    mismatches = joined_df.filter(
        (pl.col("base_inchikey") != pl.col("base_inchikey_msready")) &
        ~((pl.col("msready_smiles_generated") == "<INORGANIC>") & (pl.col("MS_READY_SMILES").is_null()))
    )

    if len(mismatches) > 0:
        # Write detailed errors to file
        with open("msready_errors.txt", "w") as f:
            f.write("MS-Ready SMILES Mismatch Report\n")
            f.write("=" * 100 + "\n\n")
            f.write("Columns:\n")
            f.write("  - base_inchikey_correct:      Expected/correct base InChIKey (from join)\n")
            f.write("  - base_inchikey_generated:    Generated base InChIKey from our MS-Ready SMILES\n")
            f.write("  - smiles_pubchem:             Original SMILES from PubChem\n")
            f.write("  - msready_smiles_dump:        MS-Ready SMILES from the dump file\n")
            f.write("  - msready_smiles_generated:   MS-Ready SMILES generated by our code\n")
            f.write("\n")
            f.write(f"Found {len(mismatches)} mismatches:\n\n")
            
            for i, row in enumerate(mismatches.iter_rows(named=True), 1):
                f.write(f"Mismatch #{i}\n")
                f.write("-" * 100 + "\n")
                f.write(f"  base_inchikey_correct:    {row['base_inchikey']}\n")
                f.write(f"  base_inchikey_generated:  {row['base_inchikey_msready']}\n")
                f.write(f"  smiles_pubchem:           {row['smiles_pubchem']}\n")
                f.write(f"  msready_smiles_dump:      {row['MS_READY_SMILES']}\n")
                f.write(f"  msready_smiles_generated: {row['msready_smiles_generated']}\n")
                f.write("\n")
        
        assert False, f"Found {len(mismatches)} mismatches. Details written to msready_errors.txt"
